[workspace]

members = [
    "day01",
    "day02",
    "day04",
    "day05",
    "day07",
    "day09",
    "day11",
    "day13",
    "day15",
    "day17",
    "day18",
    "day19",
    "day21",
    "day23",
    "intcode",
    "intcode2",
]
