[package]
name = "day13"
description = "Advent of Code 2019 - Day 13"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
intcode = { path = "../intcode" }