[package]
name = "day25"
description = "Advent of Code 2019 - Day 25"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
itertools = "0.8"
intcode2 = { path = "../intcode2" }
