[package]
name = "day12"
description = "Advent of Code 2019 - Day 12"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1.3"
num-integer = "0.1"